PANDAS LIBRARY

In [1]:
import pandas as pd

In [2]:
store=pd.read_csv(r'C:\EXCEL DATA\EXCEL 2.csv')

In [3]:
store

               Name     Product  Price   Location  Gender
0       Amit Sharma      Webcam   8652  Hyderabad    Male
1      Anjali Mehta  Microphone  49417    Kolkata  Female
2       Suresh Nair  Headphones  38283    Lucknow  Female
3       Kavita Jain       Drone   1502     Jaipur    Male
4    Rohit Malhotra  Microphone  25185      Surat    Male
..              ...         ...    ...        ...     ...
195     Kavita Jain      Laptop  22312  Hyderabad    Male
196     Priya Singh      Laptop  38863       Pune    Male
197     Pooja Joshi      Camera  57526    Chennai    Male
198     Kavita Jain    Keyboard   5310     Nagpur    Male
199    Rajeev Menon    Keyboard  47517     Nagpur    Male

[200 rows x 5 columns]

In [4]:
id(store)

3022532428528

In [6]:
store.columns

Index(['Name', 'Product', 'Price', 'Location', 'Gender'], dtype='object')

In [8]:
len(store)

200

In [9]:
len(columns)

NameError: name 'columns' is not defined

In [10]:
len(store.columns)

5

In [11]:
len(store) #used to find rows

200

In [12]:
store.dtypes

Name        object
Product     object
Price        int64
Location    object
Gender      object
dtype: object

In [13]:
store.isnull()

      Name  Product  Price  Location  Gender
0    False    False  False     False   False
1    False    False  False     False   False
2    False    False  False     False   False
3    False    False  False     False   False
4    False    False  False     False   False
..     ...      ...    ...       ...     ...
195  False    False  False     False   False
196  False    False  False     False   False
197  False    False  False     False   False
198  False    False  False     False   False
199  False    False  False     False   False

[200 rows x 5 columns]

In [15]:
store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      200 non-null    object
 1   Product   200 non-null    object
 2   Price     200 non-null    int64
 3   Location  200 non-null    object
 4   Gender    200 non-null    object
dtypes: int64(1), object(4)
memory usage: 7.9+ KB

In [16]:
store.head() #bydefault 5 rows

             Name     Product  Price   Location  Gender
0     Amit Sharma      Webcam   8652  Hyderabad    Male
1    Anjali Mehta  Microphone  49417    Kolkata  Female
2     Suresh Nair  Headphones  38283    Lucknow  Female
3     Kavita Jain       Drone   1502     Jaipur    Male
4  Rohit Malhotra  Microphone  25185      Surat    Male

In [17]:
store.head(2)

           Name     Product  Price   Location  Gender
0   Amit Sharma      Webcam   8652  Hyderabad    Male
1  Anjali Mehta  Microphone  49417    Kolkata  Female

In [18]:
store.tail() #bydefault last 5 rows

             Name   Product  Price   Location Gender
195   Kavita Jain    Laptop  22312  Hyderabad   Male
196   Priya Singh    Laptop  38863       Pune   Male
197   Pooja Joshi    Camera  57526    Chennai   Male
198   Kavita Jain  Keyboard   5310     Nagpur   Male
199  Rajeev Menon  Keyboard  47517     Nagpur   Male

In [19]:
store.tail(3)

             Name   Product  Price Location Gender
197   Pooja Joshi    Camera  57526  Chennai   Male
198   Kavita Jain  Keyboard   5310   Nagpur   Male
199  Rajeev Menon  Keyboard  47517   Nagpur   Male

In [20]:
store['Name']

0         Amit Sharma
1        Anjali Mehta
2         Suresh Nair
3         Kavita Jain
4      Rohit Malhotra
            ...
195       Kavita Jain
196       Priya Singh
197       Pooja Joshi
198       Kavita Jain
199      Rajeev Menon
Name: Name, Length: 200, dtype: object

In [21]:
store['Price']

0       8652
1      49417
2      38283
3       1502
4      25185
       ...
195    22312
196    38863
197    57526
198     5310
199    47517
Name: Price, Length: 200, dtype: int64

In [23]:
store['Name','Product']

KeyError: 'NameProduct'

In [24]:
store[['Name','Product']]

               Name     Product
0       Amit Sharma      Webcam
1      Anjali Mehta  Microphone
2       Suresh Nair  Headphones
3       Kavita Jain       Drone
4    Rohit Malhotra  Microphone
..              ...         ...
195     Kavita Jain      Laptop
196     Priya Singh      Laptop
197     Pooja Joshi      Camera
198     Kavita Jain    Keyboard
199    Rajeev Menon    Keyboard

[200 rows x 2 columns]

In [25]:
cat=store[['Name','Product','Price']]
cat

               Name     Product  Price
0       Amit Sharma      Webcam   8652
1      Anjali Mehta  Microphone  49417
2       Suresh Nair  Headphones  38283
3       Kavita Jain       Drone   1502
4    Rohit Malhotra  Microphone  25185
..              ...         ...    ...
195     Kavita Jain      Laptop  22312
196     Priya Singh      Laptop  38863
197     Pooja Joshi      Camera  57526
198     Kavita Jain    Keyboard   5310
199    Rajeev Menon    Keyboard  47517

[200 rows x 3 columns]

In [21]:
type(cat)

pandas.core.frame.DataFrame

In [26]:
len(cat.columns)

3

In [27]:
word=store[['Location','Gender']]
word

      Location  Gender
0    Hyderabad    Male
1      Kolkata  Female
2      Lucknow  Female
3       Jaipur    Male
4        Surat    Male
..         ...     ...
195  Hyderabad    Male
196       Pune    Male
197    Chennai    Male
198     Nagpur    Male
199     Nagpur    Male

[200 rows x 2 columns]

In [28]:
len(word.columns)

2

In [29]:
pd.__version__

'2.2.3'

In [30]:
store.describe()

              Price
count    200.000000
mean   31953.065000
std    16540.900461
min     1502.000000
25%    18155.250000
50%    32750.000000
75%    46020.500000
max    59732.000000

In [31]:
sentence="Hello, world ! This is a sample sentence."
words=sentence.split()
print(words)

['Hello,', 'world', '!', 'This', 'is', 'a', 'sample', 'sentence.']

In [35]:
sentence1="Hello world this is python world"
words1=sentence.split()
print(words1)

['Hello,', 'world', '!', 'This', 'is', 'a', 'sample', 'sentence.']

2nd Example of the PANDAS

In [37]:
import pandas as pd

In [38]:
country=pd.read_csv(r'C:\EXCEL DATA\countries_data.csv')

In [39]:
country

    CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Malawi          MW      35.27          44.83  Upper middle income
1        Israel          IL      19.32          26.01           Low income
2      Mongolia          MN      10.69          84.08  Upper middle income
3       Moldova          MD      13.79          59.79  Upper middle income
4       Finland          FI      22.22          26.06  Lower middle income
..          ...         ...        ...            ...                  ...
195     Belgium          BE      27.78          81.93  Lower middle income
196      Canada          CA      24.03          82.16  Upper middle income
197       Kenya          KE      10.18          42.44          High income
198     Andorra          AD      22.07          38.64          High income
199    Honduras          HN      13.77          56.23          High income

[200 rows x 5 columns]

In [40]:
len(country)

200

In [41]:
len(country)

200

In [43]:
country.shape

(200, 5)

In [44]:
country.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [45]:
country.rows

AttributeError: 'DataFrame' object has no attribute 'rows'

In [34]:
type(country)

pandas.core.frame.DataFrame

In [35]:
country

    Country Name Country Code  Birth Rate  Internet Users         Income Group
0         Malawi           MW       35.27           44.83  Upper middle income
1         Israel           IL       19.32           26.01           Low income
2       Mongolia           MN       10.69           84.08  Upper middle income
3        Moldova           MD       13.79           59.79  Upper middle income
4        Finland           FI       22.22           26.06  Lower middle income
..           ...          ...         ...             ...                  ...
195      Belgium           BE       27.78           81.93  Lower middle income
196       Canada           CA       24.03           82.16  Upper middle income
197        Kenya           KE       10.18           42.44          High income
198      Andorra           AD       22.07           38.64          High income
199     Honduras           HN       13.77           56.23          High income

[200 rows x 5 columns]

In [36]:
country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    200 non-null    object
 1   Country Code    200 non-null    object
 2   Birth Rate      200 non-null    float64
 3   Internet Users  200 non-null    float64
 4   Income Group    200 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.9+ KB

In [46]:
country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    200 non-null    object
 1   CountryCode    200 non-null    object
 2   BirthRate      200 non-null    float64
 3   InternetUsers  200 non-null    float64
 4   IncomeGroup    200 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.9+ KB

In [49]:
country.add('Salary')
country

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('float64'), dtype('<U6')) -> None

In [50]:
country.head()

  CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0      Malawi          MW      35.27          44.83  Upper middle income
1      Israel          IL      19.32          26.01           Low income
2    Mongolia          MN      10.69          84.08  Upper middle income
3     Moldova          MD      13.79          59.79  Upper middle income
4     Finland          FI      22.22          26.06  Lower middle income

In [38]:
country.tail()

    Country Name Country Code  Birth Rate  Internet Users         Income Group
195      Belgium           BE       27.78           81.93  Lower middle income
196       Canada           CA       24.03           82.16  Upper middle income
197        Kenya           KE       10.18           42.44          High income
198      Andorra           AD       22.07           38.64          High income
199     Honduras           HN       13.77           56.23          High income

In [39]:
len(country.columns)

5

In [40]:
country.shape #displays number of rows and columns

(200, 5)

In [41]:
country[::5]

,Country Name,Country Code,Birth Rate,Internet Users,Income Group
0,Malawi,MW,35.27,44.83,Upper middle income
5,China,CN,33.69,74.16,Lower middle income
10,China,CN,16.94,94.44,Low income
15,Algeria,DZ,38.22,29.15,Low income
20,Guyana,GY,36.67,72.35,Upper middle income
25,Kuwait,KW,39.33,74.65,Upper middle income
30,Moldova,MD,18.08,40.50,Low income
35,Israel,IL,20.22,30.76,Lower middle income
40,Iceland,IS,31.81,79.16,High income
45,Croatia,HR,34.63,26.60,Low income
50,Cuba,CU,15.04,92.93,Lower middle income
55,Bolivia,BO,21.10,63.49,Lower middle income
60,Finland,FI,23.27,93.05,High income
65,Australia,AU,18.54,67.12,Upper middle income
70,Indonesia,ID,19.69,23.71,Lower middle income
75,Dominican Republic,DO,37.52,69.77,Low income
80,Laos,LA,37.81,38.94,Lower middle income
85,Italy,IT,25.14,12.30,High income
90,Italy,IT,19.29,81.39,Low income
95,Colombia,CO,13.62,24.53,Upper middle income
100,Bahamas,BS,19.71,39.69,Low income
105,Mexico,MX,25.59,44.97,Low income
110,Japan,JP,38.13,59.35,Low income
115,Cyprus,CY,39.76,41.92,Upper middle income
120,Bosnia and Herzegovina,BA,21.22,48.45,Upper middle income
125,Kazakhstan,KZ,31.40,16.25,Upper middle income
130,Cambodia,KH,34.26,55.13,High income
135,Indonesia,ID,30.97,70.18,Lower middle income
140,Brazil,BR,37.31,32.55,Low income
145,Dominican Republic,DO,11.24,94.88,Lower middle income
150,Kenya,KE,37.05,54.59,Low income
155,El Salvador,SV,36.10,25.03,Upper middle income
160,Ethiopia,ET,13.87,82.58,Lower middle income
165,Iceland,IS,18.54,25.04,High income
170,Mauritania,MR,16.06,36.71,Upper middle income
175,France,FR,18.47,43.26,Low income
180,Moldova,MD,25.72,12.11,High income
185,Egypt,EG,28.30,66.74,Upper middle income
190,Mongolia,MN,12.26,32.34,Lower middle income
195,Belgium,BE,27.78,81.93,Lower middle income

In [51]:
country.describe()

        BirthRate  InternetUsers
count  200.000000     200.000000
mean    25.343950      50.602050
std      8.609407      23.792416
min     10.180000      10.510000
25%     18.292500      30.592500
50%     25.630000      48.785000
75%     33.272500      70.372500
max     39.990000      94.880000

In [43]:
country[::-1]

    Country Name Country Code  Birth Rate  Internet Users         Income Group
199     Honduras           HN       13.77           56.23          High income
198      Andorra           AD       22.07           38.64          High income
197        Kenya           KE       10.18           42.44          High income
196       Canada           CA       24.03           82.16  Upper middle income
195      Belgium           BE       27.78           81.93  Lower middle income
..           ...          ...         ...             ...                  ...
4        Finland           FI       22.22           26.06  Lower middle income
3        Moldova           MD       13.79           59.79  Upper middle income
2       Mongolia           MN       10.69           84.08  Upper middle income
1         Israel           IL       19.32           26.01           Low income
0         Malawi           MW       35.27           44.83  Upper middle income

[200 rows x 5 columns]

In [44]:
country[:5]

  Country Name Country Code  Birth Rate  Internet Users         Income Group
0       Malawi           MW       35.27           44.83  Upper middle income
1       Israel           IL       19.32           26.01           Low income
2     Mongolia           MN       10.69           84.08  Upper middle income
3      Moldova           MD       13.79           59.79  Upper middle income
4      Finland           FI       22.22           26.06  Lower middle income

In [45]:
country[:5]

  Country Name Country Code  Birth Rate  Internet Users         Income Group
0       Malawi           MW       35.27           44.83  Upper middle income
1       Israel           IL       19.32           26.01           Low income
2     Mongolia           MN       10.69           84.08  Upper middle income
3      Moldova           MD       13.79           59.79  Upper middle income
4      Finland           FI       22.22           26.06  Lower middle income

In [46]:
country[5:]

,Country Name,Country Code,Birth Rate,Internet Users,Income Group
5,China,CN,33.69,74.16,Lower middle income
6,Central African Republic,CF,14.52,13.92,Lower middle income
7,Ireland,IE,10.86,68.06,Lower middle income
8,Liberia,LR,34.90,44.09,Lower middle income
9,Indonesia,ID,16.96,39.25,High income
...,...,...,...,...,...
195,Belgium,BE,27.78,81.93,Lower middle income
196,Canada,CA,24.03,82.16,Upper middle income
197,Kenya,KE,10.18,42.44,High income
198,Andorra,AD,22.07,38.64,High income
199,Honduras,HN,13.77,56.23,High income

In [52]:
country[0:200:10]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Malawi,MW,35.27,44.83,Upper middle income
10,China,CN,16.94,94.44,Low income
20,Guyana,GY,36.67,72.35,Upper middle income
30,Moldova,MD,18.08,40.50,Low income
40,Iceland,IS,31.81,79.16,High income
50,Cuba,CU,15.04,92.93,Lower middle income
60,Finland,FI,23.27,93.05,High income
70,Indonesia,ID,19.69,23.71,Lower middle income
80,Laos,LA,37.81,38.94,Lower middle income
90,Italy,IT,19.29,81.39,Low income
100,Bahamas,BS,19.71,39.69,Low income
110,Japan,JP,38.13,59.35,Low income
120,Bosnia and Herzegovina,BA,21.22,48.45,Upper middle income
130,Cambodia,KH,34.26,55.13,High income
140,Brazil,BR,37.31,32.55,Low income
150,Kenya,KE,37.05,54.59,Low income
160,Ethiopia,ET,13.87,82.58,Lower middle income
170,Mauritania,MR,16.06,36.71,Upper middle income
180,Moldova,MD,25.72,12.11,High income
190,Mongolia,MN,12.26,32.34,Lower middle income

In [48]:
country.describe()

       Birth Rate  Internet Users
count  200.000000      200.000000
mean    25.343950       50.602050
std      8.609407       23.792416
min     10.180000       10.510000
25%     18.292500       30.592500
50%     25.630000       48.785000
75%     33.272500       70.372500
max     39.990000       94.880000

In [49]:
country.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Birth Rate,200.0,25.34395,8.609407,10.18,18.2925,25.630,33.2725,39.99
Internet Users,200.0,50.60205,23.792416,10.51,30.5925,48.785,70.3725,94.88

In [50]:
country.columns()

TypeError: 'Index' object is not callable

In [51]:
country[:]

    Country Name Country Code  Birth Rate  Internet Users         Income Group
0         Malawi           MW       35.27           44.83  Upper middle income
1         Israel           IL       19.32           26.01           Low income
2       Mongolia           MN       10.69           84.08  Upper middle income
3        Moldova           MD       13.79           59.79  Upper middle income
4        Finland           FI       22.22           26.06  Lower middle income
..           ...          ...         ...             ...                  ...
195      Belgium           BE       27.78           81.93  Lower middle income
196       Canada           CA       24.03           82.16  Upper middle income
197        Kenya           KE       10.18           42.44          High income
198      Andorra           AD       22.07           38.64          High income
199     Honduras           HN       13.77           56.23          High income

[200 rows x 5 columns]

In [52]:
country.head(20)

,Country Name,Country Code,Birth Rate,Internet Users,Income Group
0,Malawi,MW,35.27,44.83,Upper middle income
1,Israel,IL,19.32,26.01,Low income
2,Mongolia,MN,10.69,84.08,Upper middle income
3,Moldova,MD,13.79,59.79,Upper middle income
4,Finland,FI,22.22,26.06,Lower middle income
5,China,CN,33.69,74.16,Lower middle income
6,Central African Republic,CF,14.52,13.92,Lower middle income
7,Ireland,IE,10.86,68.06,Lower middle income
8,Liberia,LR,34.90,44.09,Lower middle income
9,Indonesia,ID,16.96,39.25,High income
10,China,CN,16.94,94.44,Low income
11,Afghanistan,AF,11.92,89.93,Lower middle income
12,Luxembourg,LU,16.10,46.30,High income
13,Cameroon,CM,37.24,62.08,Upper middle income
14,Bangladesh,BD,15.05,68.49,Upper middle income
15,Algeria,DZ,38.22,29.15,Low income
16,Germany,DE,28.14,49.04,Upper middle income
17,China,CN,13.04,92.03,Lower middle income
18,Maldives,MV,29.12,35.86,Low income
19,Botswana,BW,36.89,42.66,Low income

In [53]:
country.isnull().sum()

Country Name      0
Country Code      0
Birth Rate        0
Internet Users    0
Income Group      0
dtype: int64

In [53]:
country.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [56]:
country.dtypes

Country Name       object
Country Code       object
Birth Rate        float64
Internet Users    float64
Income Group       object
dtype: object

In [54]:
country.dtypes

CountryName       object
CountryCode       object
BirthRate        float64
InternetUsers    float64
IncomeGroup       object
dtype: object

In [57]:
country.columns

Index(['Country Name', 'Country Code', 'Birth Rate', 'Internet Users',
       'Income Group'],
      dtype='object')

In [59]:
country

    CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Malawi          MW      35.27          44.83  Upper middle income
1        Israel          IL      19.32          26.01           Low income
2      Mongolia          MN      10.69          84.08  Upper middle income
3       Moldova          MD      13.79          59.79  Upper middle income
4       Finland          FI      22.22          26.06  Lower middle income
..          ...         ...        ...            ...                  ...
195     Belgium          BE      27.78          81.93  Lower middle income
196      Canada          CA      24.03          82.16  Upper middle income
197       Kenya          KE      10.18          42.44          High income
198     Andorra          AD      22.07          38.64          High income
199    Honduras          HN      13.77          56.23          High income

[200 rows x 5 columns]

In [61]:
country_categorical = country[['Country Name', 'Country Code', 'Income Group']]
country_categorical.head()

KeyError: "None of [Index(['Country Name', 'Country Code', 'Income Group'], dtype='object')] are in the [columns]"

In [62]:
country.num=country[['Birth Rate', 'Internet Users']]
country.num.head()

KeyError: "None of [Index(['Birth Rate', 'Internet Users'], dtype='object')] are in the [columns]"

In [63]:
country.num.describe()

AttributeError: 'DataFrame' object has no attribute 'num'

In [58]:
country['Income Group']

KeyError: 'Income Group'

In [64]:
country[['Country Name', 'Birth Rate']]

KeyError: "None of [Index(['Country Name', 'Birth Rate'], dtype='object')] are in the [columns]"

In [72]:
country[['Country Name', 'Birth Rate', 'Income Group']]

    Country Name  Birth Rate         Income Group
0         Malawi       35.27  Upper middle income
1         Israel       19.32           Low income
2       Mongolia       10.69  Upper middle income
3        Moldova       13.79  Upper middle income
4        Finland       22.22  Lower middle income
..           ...         ...                  ...
195      Belgium       27.78  Lower middle income
196       Canada       24.03  Upper middle income
197        Kenya       10.18          High income
198      Andorra       22.07          High income
199     Honduras       13.77          High income

[200 rows x 3 columns]

In [65]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [66]:
country1=pd.read_csv(r"C:\EXCEL DATA\EXCEL 2.csv")

In [67]:
country1

               Name     Product  Price   Location  Gender
0       Amit Sharma      Webcam   8652  Hyderabad    Male
1      Anjali Mehta  Microphone  49417    Kolkata  Female
2       Suresh Nair  Headphones  38283    Lucknow  Female
3       Kavita Jain       Drone   1502     Jaipur    Male
4    Rohit Malhotra  Microphone  25185      Surat    Male
..              ...         ...    ...        ...     ...
195     Kavita Jain      Laptop  22312  Hyderabad    Male
196     Priya Singh      Laptop  38863       Pune    Male
197     Pooja Joshi      Camera  57526    Chennai    Male
198     Kavita Jain    Keyboard   5310     Nagpur    Male
199    Rajeev Menon    Keyboard  47517     Nagpur    Male

[200 rows x 5 columns]

In [68]:
country1[4:8][['Product', 'Price']]

      Product  Price
4  Microphone  25185
5      Webcam  40277
6      Mobile   4649
7      Camera  21571

In [71]:
country1[['Product','Price']][4:8]

      Product  Price
4  Microphone  25185
5      Webcam  40277
6      Mobile   4649
7      Camera  21571

In [72]:
country_data=country1[['Product', 'Price']]
country_data

        Product  Price
0        Webcam   8652
1    Microphone  49417
2    Headphones  38283
3         Drone   1502
4    Microphone  25185
..          ...    ...
195      Laptop  22312
196      Laptop  38863
197      Camera  57526
198    Keyboard   5310
199    Keyboard  47517

[200 rows x 2 columns]

In [74]:
country1.Product  * country1.Price

0      WebcamWebcamWebcamWebcamWebcamWebcamWebcamWebc...
1      MicrophoneMicrophoneMicrophoneMicrophoneMicrop...
2      HeadphonesHeadphonesHeadphonesHeadphonesHeadph...
3      DroneDroneDroneDroneDroneDroneDroneDroneDroneD...
4      MicrophoneMicrophoneMicrophoneMicrophoneMicrop...
                             ...
195    LaptopLaptopLaptopLaptopLaptopLaptopLaptopLapt...
196    LaptopLaptopLaptopLaptopLaptopLaptopLaptopLapt...
197    CameraCameraCameraCameraCameraCameraCameraCame...
198    KeyboardKeyboardKeyboardKeyboardKeyboardKeyboa...
199    KeyboardKeyboardKeyboardKeyboardKeyboardKeyboa...
Length: 200, dtype: object

In [77]:
country1['mycalc']=country1['Product '] * country['Price']  # to add new data in existing data

KeyError: 'Product '

In [83]:
country['mycalc']=country.Birth Rate * country.Internet Users  #to add new data in existing data set

SyntaxError: invalid syntax (2864417392.py, line 1)

In [84]:
country

    Country Name Country Code  Birth Rate  Internet Users         Income Group
0         Malawi           MW       35.27           44.83  Upper middle income
1         Israel           IL       19.32           26.01           Low income
2       Mongolia           MN       10.69           84.08  Upper middle income
3        Moldova           MD       13.79           59.79  Upper middle income
4        Finland           FI       22.22           26.06  Lower middle income
..           ...          ...         ...             ...                  ...
195      Belgium           BE       27.78           81.93  Lower middle income
196       Canada           CA       24.03           82.16  Upper middle income
197        Kenya           KE       10.18           42.44          High income
198      Andorra           AD       22.07           38.64          High income
199     Honduras           HN       13.77           56.23          High income

[200 rows x 5 columns]

In [86]:
country.columns[3:4]

Index(['Internet Users'], dtype='object')

In [87]:
country[::10]

,Country Name,Country Code,Birth Rate,Internet Users,Income Group
0,Malawi,MW,35.27,44.83,Upper middle income
10,China,CN,16.94,94.44,Low income
20,Guyana,GY,36.67,72.35,Upper middle income
30,Moldova,MD,18.08,40.50,Low income
40,Iceland,IS,31.81,79.16,High income
50,Cuba,CU,15.04,92.93,Lower middle income
60,Finland,FI,23.27,93.05,High income
70,Indonesia,ID,19.69,23.71,Lower middle income
80,Laos,LA,37.81,38.94,Lower middle income
90,Italy,IT,19.29,81.39,Low income
100,Bahamas,BS,19.71,39.69,Low income
110,Japan,JP,38.13,59.35,Low income
120,Bosnia and Herzegovina,BA,21.22,48.45,Upper middle income
130,Cambodia,KH,34.26,55.13,High income
140,Brazil,BR,37.31,32.55,Low income
150,Kenya,KE,37.05,54.59,Low income
160,Ethiopia,ET,13.87,82.58,Lower middle income
170,Mauritania,MR,16.06,36.71,Upper middle income
180,Moldova,MD,25.72,12.11,High income
190,Mongolia,MN,12.26,32.34,Lower middle income

In [88]:
country

    Country Name Country Code  Birth Rate  Internet Users         Income Group
0         Malawi           MW       35.27           44.83  Upper middle income
1         Israel           IL       19.32           26.01           Low income
2       Mongolia           MN       10.69           84.08  Upper middle income
3        Moldova           MD       13.79           59.79  Upper middle income
4        Finland           FI       22.22           26.06  Lower middle income
..           ...          ...         ...             ...                  ...
195      Belgium           BE       27.78           81.93  Lower middle income
196       Canada           CA       24.03           82.16  Upper middle income
197        Kenya           KE       10.18           42.44          High income
198      Andorra           AD       22.07           38.64          High income
199     Honduras           HN       13.77           56.23          High income

[200 rows x 5 columns]

In [89]:
country[3:4]

  Country Name Country Code  Birth Rate  Internet Users         Income Group
3      Moldova           MD       13.79           59.79  Upper middle income

In [90]:
country[3:3]

Empty DataFrame
Columns: [Country Name, Country Code, Birth Rate, Internet Users, Income Group]
Index: []

In [91]:
country[3:2]

Empty DataFrame
Columns: [Country Name, Country Code, Birth Rate, Internet Users, Income Group]
Index: []

In [92]:
country[3:5]

  Country Name Country Code  Birth Rate  Internet Users         Income Group
3      Moldova           MD       13.79           59.79  Upper middle income
4      Finland           FI       22.22           26.06  Lower middle income

In [93]:
country[3,4]

KeyError: (3, 4)

In [81]:
country.loc[[3,5]]

  CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
3     Moldova          MD      13.79          59.79  Upper middle income
5       China          CN      33.69          74.16  Lower middle income

In [1]:
import pandas as pd

In [2]:
country=pd.read_csv(r'C:\EXCEL DATA\countries_data.csv')

In [3]:
country

    Country Name Country Code  Birth Rate  Internet Users         Income Group
0         Malawi           MW       35.27           44.83  Upper middle income
1         Israel           IL       19.32           26.01           Low income
2       Mongolia           MN       10.69           84.08  Upper middle income
3        Moldova           MD       13.79           59.79  Upper middle income
4        Finland           FI       22.22           26.06  Lower middle income
..           ...          ...         ...             ...                  ...
195      Belgium           BE       27.78           81.93  Lower middle income
196       Canada           CA       24.03           82.16  Upper middle income
197        Kenya           KE       10.18           42.44          High income
198      Andorra           AD       22.07           38.64          High income
199     Honduras           HN       13.77           56.23          High income

[200 rows x 5 columns]

In [82]:
country.InternetUsers<2

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: InternetUsers, Length: 200, dtype: bool

In [83]:
country

    CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Malawi          MW      35.27          44.83  Upper middle income
1        Israel          IL      19.32          26.01           Low income
2      Mongolia          MN      10.69          84.08  Upper middle income
3       Moldova          MD      13.79          59.79  Upper middle income
4       Finland          FI      22.22          26.06  Lower middle income
..          ...         ...        ...            ...                  ...
195     Belgium          BE      27.78          81.93  Lower middle income
196      Canada          CA      24.03          82.16  Upper middle income
197       Kenya          KE      10.18          42.44          High income
198     Andorra          AD      22.07          38.64          High income
199    Honduras          HN      13.77          56.23          High income

[200 rows x 5 columns]

In [84]:
import pandas as pd

In [85]:
country=pd.read_csv("C:\EXCEL DATA\countries_data.csv")
country

    CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Malawi          MW      35.27          44.83  Upper middle income
1        Israel          IL      19.32          26.01           Low income
2      Mongolia          MN      10.69          84.08  Upper middle income
3       Moldova          MD      13.79          59.79  Upper middle income
4       Finland          FI      22.22          26.06  Lower middle income
..          ...         ...        ...            ...                  ...
195     Belgium          BE      27.78          81.93  Lower middle income
196      Canada          CA      24.03          82.16  Upper middle income
197       Kenya          KE      10.18          42.44          High income
198     Andorra          AD      22.07          38.64          High income
199    Honduras          HN      13.77          56.23          High income

[200 rows x 5 columns]

In [86]:
country.InternetUsers<2 #we are checking gien conditions if its correct true or false

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: InternetUsers, Length: 200, dtype: bool

In [6]:
import internet users as internet

SyntaxError: invalid syntax (3004134184.py, line 1)

In [87]:
country.InternetUsers<2

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: InternetUsers, Length: 200, dtype: bool

In [8]:
Filter=country.InternetUsers <2
Filter

AttributeError: 'DataFrame' object has no attribute 'InternetUsers'

In [88]:
country[Filter]

NameError: name 'Filter' is not defined

In [91]:
#Filter and Filte2
Filter & Filter2

NameError: name 'Filter' is not defined

In [92]:
country[Filter & Filter2]

NameError: name 'Filter' is not defined

In [93]:
country.head()

  CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0      Malawi          MW      35.27          44.83  Upper middle income
1      Israel          IL      19.32          26.01           Low income
2    Mongolia          MN      10.69          84.08  Upper middle income
3     Moldova          MD      13.79          59.79  Upper middle income
4     Finland          FI      22.22          26.06  Lower middle income

In [10]:
country

SyntaxError: invalid syntax (719491132.py, line 1)

In [12]:
country[(country.Birth Rate >40) & (country.Internet Users <2)]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2095895811.py, line 1)

In [14]:
country.([Filter=='Low Income'])

SyntaxError: invalid syntax (681101672.py, line 1)

In [94]:
import pandas as pd

In [95]:
country=pd.read_csv("C:\EXCEL DATA\countries_data.csv")

In [96]:
country

    CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Malawi          MW      35.27          44.83  Upper middle income
1        Israel          IL      19.32          26.01           Low income
2      Mongolia          MN      10.69          84.08  Upper middle income
3       Moldova          MD      13.79          59.79  Upper middle income
4       Finland          FI      22.22          26.06  Lower middle income
..          ...         ...        ...            ...                  ...
195     Belgium          BE      27.78          81.93  Lower middle income
196      Canada          CA      24.03          82.16  Upper middle income
197       Kenya          KE      10.18          42.44          High income
198     Andorra          AD      22.07          38.64          High income
199    Honduras          HN      13.77          56.23          High income

[200 rows x 5 columns]

In [97]:
country.InternetUsers<2

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: InternetUsers, Length: 200, dtype: bool

In [19]:
Filter=country.InternetUsers<2
Filter

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: InternetUsers, Length: 200, dtype: bool

In [98]:
country[Filter]

NameError: name 'Filter' is not defined

In [99]:
len(country[Filter])

NameError: name 'Filter' is not defined

In [100]:
country.BirthRate>40

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: BirthRate, Length: 200, dtype: bool

In [101]:
country.BirthRate>40

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: BirthRate, Length: 200, dtype: bool

In [102]:
Filter2= country.BirthRate>40
Filter2

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: BirthRate, Length: 200, dtype: bool

In [27]:
country[Filter2]

Empty DataFrame
Columns: [CountryName, CountryCode, BirthRate, InternetUsers, IncomeGroup]
Index: []

In [103]:
len(Filter2)

200

In [104]:
#Filter and Filter2
Filter & Filter2

NameError: name 'Filter' is not defined

In [105]:
country[Filter & Filter2]
country=country1
country1

NameError: name 'Filter' is not defined

In [106]:
country[(country.BirthRate>40)  &  (country.InternetUsers <2)]
country

    CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Malawi          MW      35.27          44.83  Upper middle income
1        Israel          IL      19.32          26.01           Low income
2      Mongolia          MN      10.69          84.08  Upper middle income
3       Moldova          MD      13.79          59.79  Upper middle income
4       Finland          FI      22.22          26.06  Lower middle income
..          ...         ...        ...            ...                  ...
195     Belgium          BE      27.78          81.93  Lower middle income
196      Canada          CA      24.03          82.16  Upper middle income
197       Kenya          KE      10.18          42.44          High income
198     Andorra          AD      22.07          38.64          High income
199    Honduras          HN      13.77          56.23          High income

[200 rows x 5 columns]

In [40]:
Filter & Filter2

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Length: 200, dtype: bool

In [41]:
country[Filter & Filter2]

Empty DataFrame
Columns: [CountryName, CountryCode, BirthRate, InternetUsers, IncomeGroup]
Index: []

In [107]:
country[country.IncomeGroup == 'Low income']

            CountryName CountryCode  BirthRate  InternetUsers IncomeGroup
1                Israel          IL      19.32          26.01  Low income
10                China          CN      16.94          94.44  Low income
15              Algeria          DZ      38.22          29.15  Low income
18             Maldives          MV      29.12          35.86  Low income
19             Botswana          BW      36.89          42.66  Low income
24               Cyprus          CY      18.97          14.75  Low income
27                Libya          LY      29.90          18.15  Low income
30              Moldova          MD      18.08          40.50  Low income
31              Belarus          BY      33.49          68.54  Low income
32              Andorra          AD      18.30          64.19  Low income
33              Bahrain          BH      26.76          28.16  Low income
37           Azerbaijan          AZ      19.97          49.86  Low income
45              Croatia          HR      34.63          26.60  Low income
46            Australia          AU      20.75          48.53  Low income
57              Ireland          IE      39.09          36.38  Low income
64                 Mali          ML      23.48          43.62  Low income
75   Dominican Republic          DO      37.52          69.77  Low income
83                China          CN      33.31          76.25  Low income
84           Kazakhstan          KZ      37.25          94.34  Low income
87               Guyana          GY      16.77          70.95  Low income
89               Belize          BZ      23.56          68.56  Low income
90                Italy          IT      19.29          81.39  Low income
97              Finland          FI      27.13          53.78  Low income
100             Bahamas          BS      19.71          39.69  Low income
101            Bulgaria          BG      31.25          75.22  Low income
102              Cyprus          CY      26.54          67.09  Low income
105              Mexico          MX      25.59          44.97  Low income
109              Israel          IL      32.82          42.41  Low income
110               Japan          JP      38.13          59.35  Low income
119             Finland          FI      25.29          73.21  Low income
131            Bulgaria          BG      25.09          90.05  Low income
133              Latvia          LV      24.53          40.90  Low income
139             Algeria          DZ      18.56          17.26  Low income
140              Brazil          BR      37.31          32.55  Low income
141             Belgium          BE      29.87          50.92  Low income
150               Kenya          KE      37.05          54.59  Low income
156  Dominican Republic          DO      15.87          33.64  Low income
166              Israel          IL      17.00          39.19  Low income
168          Azerbaijan          AZ      28.23          36.38  Low income
169              Guinea          GN      39.58          77.81  Low income
175              France          FR      18.47          43.26  Low income
178            Cambodia          KH      39.42          51.05  Low income
182             Estonia          EE      18.64          11.94  Low income
183               Ghana          GH      22.20          51.73  Low income
184             Estonia          EE      15.78          82.30  Low income
191          Madagascar          MG      36.71          30.33  Low income
193              Brunei          BN      25.69          23.59  Low income

In [48]:
country[country.IncomeGroup == 'Low income']
type(country)

pandas.core.frame.DataFrame

In [45]:
country.IncomeGroup.unique() # to get the unique categories

array(['Upper middle income', 'Low income', 'Lower middle income',
       'High income'], dtype=object)

In [ ]:
country[country.IncomeGroup

In [52]:
country.IncomeGroup.nunique()

4

InTRODUCTION